
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'
DONE = 'Done'
FOUND = 'FOUND'

BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN, FOUND, DONE]

GOAL_SUCCESS_REWARD = 5
FOUND_SUCCESS_REWARD=2.5
STEP_PENALTY = -0.01
FAILED_ACTION_PENALTY = 0
